version: "2"

linters:
  enable:
    - copyloopvar
    - errorlint
    - misspell
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - usestdlibvars

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/jhayashi1/ascii-tui)
